name: Build Rootfs Cache

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'master'

jobs:  
  do-it:
    uses: armbian/build/.github/workflows/build-cache.yml@master
  test:
    uses: armbian/build/.github/workflows/build-cache.yml@master
