name: Build Rootfs Cache

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'master'

jobs:  
  armhf:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'bananapi'
  aarch64:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'lepotato'
  amd64:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'uefi-x86'
