# This composite actions calls build rootfs action from git@github.com:armbian/scripts.git three times so we 
# can run all rootfs combinations at once - depending of available runners

name: Build rootfs caches

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'nightly'

jobs:

  merge:
    uses: armbian/scripts/.github/workflows/merge-from-branch.yml@master
    with:
      branch: 'nightly'
    secrets:  
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}

  find:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Armbian' }}
    strategy:
      matrix: 
        board: [bananapi, lepotato, uefi-x86]
    steps:
      - uses: armbian/scripts/.github/workflows/build-rootfs-cache.yml@master
        with:
          rootfsarch: ${{ matrix.board }}
          branch: ${{ github.event.inputs.branch }}
        secrets:  
          GPG_KEY1: ${{ secrets.GPG_KEY1 }}
          GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
          GPG_KEY2: ${{ secrets.GPG_KEY2 }}
          GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
          SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
