name: Build Rootfs Cache

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'master'

jobs:

  Merge:

    name: "Merge master into nightly"
    runs-on: [self-hosted, Linux]
    if: ${{ github.repository_owner == 'Armbian' }}

    steps:

      - name: Checkout Armbian build script
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: nightly
          clean: false

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY2 }}
          passphrase: ${{ secrets.GPG_PASSPHRASE2 }}
          workdir: build
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Merge master into nightly

        run: |
          cd build
          git config --global user.email "info@armbian.com"
          git config --global user.name "Armbianworker"
          git checkout master
          git fetch
          git merge origin/master
          git checkout nightly
          git merge master nightly
          git push

  armhf:
    needs: [ Merge ]
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'bananapi'
      branch: ${{ inputs.branch }}
    secrets:  
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
  aarch64:
    needs: [ Merge ]
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'lepotato'
      branch: ${{ inputs.branch }}
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
  amd64:
    needs: [ Merge ]
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'uefi-x86'
      branch: ${{ inputs.branch }}
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}

  jobsend:
    name: Finish
    needs: [armhf,aarch64,amd64]
    runs-on: [ubuntu-latest]
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:
      - name: Fix permissions
        run: |
          echo "End"
