name: Build Rootfs Cache

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'master'

jobs:  
  armhf:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'bananapi'
    secrets:  
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: '1234'
  aarch64:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'lepotato'
    secrets:
      GPG_KEY2: '1234'
      GPG_PASSPHRASE2: '1234'
  amd64:
    uses: armbian/build/.github/workflows/build-cache.yml@test
    with:
      rootfsarch: 'uefi-x86'
    secrets:
      GPG_KEY2: '1234'
      GPG_PASSPHRASE2: '1234'
