name: Build Rootfs Cache

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'master'

jobs:

  gradle:
    strategy:
      fail-fast: false
      matrix:
        board: [lepotato,bananapi,uefi-x86]
    name: Variant
    runs-on: [self-hosted, Linux]
    steps:

      - name: Sync
        run: |
          echo "test"
    
      - name: ftp deploy
        uses: armbian/build/build-cache@master
